version: "3"
services:
  db:
    image: postgres:14.1-bullseye
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    
